### ISSUE TITLE
Relative folder location for setting cph.general.saveLocation doesn't work

### ISSUE THREAD

**Issue by JackKorman** [agrawal-d/cph#162]
Relative folder location doesn't seem to work for the setting `cph.general.saveLocation`. It seems the extension breaks when I try. The `CPH JUDGE: RESULTS` becomes empty, I can't add any new testcases, the `<+>` button in the browser doesn't work either, until I remove the folder location or add the full path to the folder location.

This is what I mean by `CPH JUDGE: RESULTS` being empty, clicking `+Create Problem` doesn't work,
![CPH JUDGE: RESULTS](https://user-images.githubusercontent.com/85828537/121805408-fe4e2300-cc6c-11eb-9442-6328ddb3ea06.png)

Things I had tried,
>.\\.cph
>${fileDirname}\\.cph

I wanted the `<.bin>` files to also be in the `.cph` folder, so the parent folder stays clean.

**Extension Version:** `v5.7.1`

**VS Code Version:** `v1.57`

**Browser Version:** `Chrome Version 91.0.4472.77 (Official Build) (64-bit)`

**Operating System:** `Windows 10, 64bit`

**Comment by agrawal-d** [comment]
Hi, thanks for creating the issue.

Yeah, relative paths don't work since the settings are not aware of the context.
However, you may find Workspace-specific settings useful, they apply to a specific workplace ( usually a folder ) only. Feel free to reopen the issue if you have any more questions.

https://code.visualstudio.com/docs/getstarted/settings.
