### ISSUE TITLE
Showing failed even when the recieved output is same as the expected output

### ISSUE THREAD

**Issue by AksPa28** [agrawal-d/cph#183]
Even though after compiling the answer is right it shows failed in the output column.
I am coding in CPP.
See attached image for a clear explanation.

**Extension Version:**  v5.8.5
**VS Code Version:** 1.58.2

**Browser Version:** Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)

**Operating System:**  Windows 10 64 bit

**Comment by AksPa28** [comment]
![Screenshot 2021-08-01 011416](https://user-images.githubusercontent.com/69463417/127751052-d3dcdb99-a414-486d-8af7-d57b310e2a36.png)

**Comment by agrawal-d** [comment]
Can you please share the full code, and the full testcase? 

You can share an ideone.com run link.

**Comment by Lakshit-Chiranjiv** [comment]
@AksPa28 I ran your same code , and it ran successfully and even the judge puts it as passed. I guess you should remove your input and enter your testcase again number by number...don't copy-paste it....try it once... it may work
if even that doesn't work then try reinstalling cph
![ran](https://user-images.githubusercontent.com/69780029/128552412-0c42ca89-a1bd-4147-b782-74e6ea4b54d5.jpg)
here is the code I compiled

```
#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

int main()
{
    ios_base::sync_with_stdio(false) ;
    cin.tie(NULL);
    cout.tie(NULL);
    ll t, n, i;
    cin>>t;
    while(t--){
        cin>>n;
        ll a[n], sum=0, cnt;
        for (i=0; i<n;++i){
            cin>>a[i];
        }
        unordered_map<ll, ll> mp;
        for (i=0;i<n;++i)
            mp[a[i]]++;
        for (auto it : mp){
            if(it.second>1){
                cnt = it.second*(n-it.second);
                sum+=cnt;
            }
            else{
                sum+=n-1;
            }
        }
    cout<<sum<<"\n";
    }
    return 0;
}
```

the testcase :

```
2
3
4 2 4
6
2 8 6 2 1 5
```

I have put the code and testcase for you @agrawal-d  so that you can also give it a try
if the error persists....let me know @AksPa28
