### ISSUE TITLE
Does not download the testcase

### ISSUE THREAD

**Issue by camilojm27** [agrawal-d/cph#41]
**Extension Version:** <4.0.2>
**VS Code Version:** <Version: 1.45.1
OS: Linux x64 5.4.45-1-lts snap>

**Comment by agrawal-d** [comment]
I'll need more information to help you. Please describe in detail the steps you took, what you expected and what actually happened.

Divyanshu Agrawal

________________________________

**Comment by camilojm27** [comment]
I commented that i don't know why does not appear xd. github error
Any way i am hoping this (3.4.5) 
![image](https://user-images.githubusercontent.com/14319090/84225503-e74a8300-aaa4-11ea-80b7-3a2f436adaa5.png)
but i get this in 4.0.2
![image](https://user-images.githubusercontent.com/14319090/84225560-0fd27d00-aaa5-11ea-8189-79f49171211c.png)
i don't know what happens if doesn't use the download data or just don't download it.

**Comment by agrawal-d** [comment]
If I understood you correctly, the problem is being parsed on clicking the companion button and results window is showing up, but no testcases?

I just tried out the same problem, and it works for me.
You can see if companion is the source of the problem:

- Go to the settings of competitive companion and enable debug mode.
- Then open browser developer console ( Ctrl+Shift+I)
- Activate companion
- There should be the output of parsed problem.

Please share that console output here.

**Comment by camilojm27** [comment]
Hi, i think the problem it's because i am trying with the mechanism of the old version (with the link commented) and this new version requires the extension, so if someone has the link commented on the top of the file doesn't work, you need to download the browser extension mandatory.
Other Words there's no backwards compatibility.

**Comment by agrawal-d** [comment]
Oh yes, I've removed that functionality now. You neee to use the companion extension to download testcases. Instructions are in the readme.
