### ISSUE TITLE
undefined reference to main

### ISSUE THREAD

**Issue by AC-BOSS** [agrawal-d/cph#46]
When I click run tests after parsing task, I get the error "in function _start undefined reference to main"
**Extension Version:** 2.17.0
**VS Code Version:** cd9ea648

**Comment by agrawal-d** [comment]
Thanks for the report, @AC-BOSS. To help debug this problem, please share with me:
- the full source code of the problem
- the operating system
- the compiler version

At a glance, it seems like it may be a problem with the code rather than with the extension. Are you able to compile & run it manually?

**Comment by AC-BOSS** [comment]
Well that error was coming up because I clicked run without saving. You don't save on online IDEs, hence the mistake.
