### ISSUE TITLE
Server Time Out without any reason.The code gets compiled on any other ide within a second, but SIGTERM error occurs while running it on CPH.

### ISSUE THREAD

**Issue by ivanganatra** [agrawal-d/cph#88]
VS Code Version:1.50.1
64 Bit Operating System

**Comment by agrawal-d** [comment]
Can you share the extension version and the full code that causes this issue?

**Comment by saransh2708** [comment]
facing same problem version of extension 5.7.1
![image](https://user-images.githubusercontent.com/69115790/122739887-0c212b00-d2a1-11eb-8362-6979e76f0076.png)
This usually happens when I run my code for the first time. On my previous device everything was running smoothly.

**Comment by KnoxArrow** [comment]
For all those people experiencing SIGTERM error on first time execution . You can try disabling your antivirus . I was also experiencing this issue from a long time but after numerous adjustments to vscode settings and installing different versions and trying all the default settings. I finally decided to disable my MaCfee antivirus which was preinstalled on my hp laptop. and now it is  working smoothly. u can also try exclusion list of your antivirus because antivirus could be slowing down your program execution .

**Comment by KnoxArrow** [comment]
@agrawal-d  bro you can close this issue as well.

**Comment by HNazmul-IV** [comment]
> For all those people experiencing SIGTERM error on first time execution . You can try disabling your antivirus . I was also experiencing this issue from a long time but after numerous adjustments to vscode settings and installing different versions and trying all the default settings. I finally decided to disable my MaCfee antivirus which was preinstalled on my hp laptop. and now it is working smoothly. u can also try exclusion list of your antivirus because antivirus could be slowing down your program execution .

Hey, Why We should disable our Anti virus. it always help us to keep our computer safe.  Try to fix this issue in exact way.

**Comment by KnoxArrow** [comment]
> > For all those people experiencing SIGTERM error on first time execution . You can try disabling your antivirus . I was also experiencing this issue from a long time but after numerous adjustments to vscode settings and installing different versions and trying all the default settings. I finally decided to disable my MaCfee antivirus which was preinstalled on my hp laptop. and now it is working smoothly. u can also try exclusion list of your antivirus because antivirus could be slowing down your program execution .
> 
> Hey, Why We should disable our Anti virus. it always help us to keep our computer safe. Try to fix this issue in exact way.

You can refer [this](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26#:~:text=Go%20to%20Start%20%3E%20Settings%20%3E%20Update,%2C%20file%20types%2C%20or%20process.) if you don't want to Disable Antivirus, You can add the folder containing your Code to Exclusion List So that the Antivirus does not slow down the running of your Code resulting into SIGTERM Error on first execution.

**Comment by TashinParvez** [comment]
> > > For all those people experiencing SIGTERM error on first time execution . You can try disabling your antivirus . I was also experiencing this issue from a long time but after numerous adjustments to vscode settings and installing different versions and trying all the default settings. I finally decided to disable my MaCfee antivirus which was preinstalled on my hp laptop. and now it is working smoothly. u can also try exclusion list of your antivirus because antivirus could be slowing down your program execution .
> > 
> > 
> > Hey, Why We should disable our Anti virus. it always help us to keep our computer safe. Try to fix this issue in exact way.
> 
> You can refer [this](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26#:~:text=Go%20to%20Start%20%3E%20Settings%20%3E%20Update,%2C%20file%20types%2C%20or%20process.) if you don't want to Disable Antivirus, You can add the folder containing your Code to Exclusion List So that the Antivirus does not slow down the running of your Code resulting into SIGTERM Error on first execution.

Thank you, it solved my Problem.

**Comment by raj-mistry-01** [comment]
@KnoxArrow 

Thanks for the solution.
